exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("Users")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("Users").insert([
        {
          N_Id: 1000000001,
          name: "أحمد عادل",
          email: "ahmed.adel@gmail.com",
          gender: "Male",
          age: 30,
          city: "الزرقاء",
          religion: "الإسلام",
          polling_address: "شارع النيل",
          isOrganizer: false,
          password: "password123",
          otp: "123456",
          token: "token1",
          circle_id: 3,
        },
        {
          N_Id: 1000000002,
          name: "فاطمة الزهراء",
          email: "fatima.zahra@gmail.com",
          gender: "Female",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع البحر",
          isOrganizer: true,
          password: "password123",
          otp: "234567",
          token: "token2",
          circle_id: 2,
        },
        {
          N_Id: 1000000003,
          name: "محمد علي",
          email: "mohamed.ali@gmail.com",
          gender: "Male",
          age: 35,
          city: "الزرقاء",
          religion: "الإسلام",
          polling_address: "شارع الملك",
          isOrganizer: false,
          password: "password123",
          otp: "345678",
          token: "token3",
          circle_id: 3,
        },
        {
          N_Id: 1000000004,
          name: "سارة محمد",
          email: "sara.mohamed@gmail.com",
          gender: "Female",
          age: 32,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الأمير",
          isOrganizer: true,
          password: "password123",
          otp: "456789",
          token: "token4",
          circle_id: 1,
        },
        {
          N_Id: 1000000005,
          name: "علي حسن",
          email: "ali.hassan@gmail.com",
          gender: "Male",
          age: 40,
          city: "الزرقاء",
          religion: "الإسلام",
          polling_address: "شارع الخليج",
          isOrganizer: false,
          password: "password123",
          otp: "567890",
          token: "token5",
          circle_id: 3,
        },
        {
          N_Id: 1000000006,
          name: "آية أحمد",
          email: "aya.ahmed@gmail.com",
          gender: "Female",
          age: 29,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع النصر",
          isOrganizer: true,
          password: "password123",
          otp: "678901",
          token: "token6",
          circle_id: 1,
        },
        {
          N_Id: 1000000007,
          name: "حسن عبد الله",
          email: "hassan.abdullah@gmail.com",
          gender: "Male",
          age: 33,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الحمرا",
          isOrganizer: false,
          password: "password123",
          otp: "789012",
          token: "token7",
          circle_id: 1,
        },
        {
          N_Id: 1000000008,
          name: "نجلاء عبد العزيز",
          email: "najlaa.abdelaziz@gmail.com",
          gender: "Female",
          age: 31,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الملك حسين",
          isOrganizer: true,
          password: "password123",
          otp: "890123",
          token: "token8",
          circle_id: 2,
        },
        {
          N_Id: 1000000009,
          name: " سامي كارلوس",
          email: "youssef.sami@gmail.com",
          gender: "Male",
          age: 38,
          city: "الزرقاء",
          religion: "المسيحية",
          polling_address: "شارع الوفاء",
          isOrganizer: false,
          password: "password123",
          otp: "901234",
          token: "token9",
          circle_id: 3,
        },
        {
          N_Id: 1000000010,
          name: "منى جمال",
          email: "mona.jamal@gmail.com",
          gender: "Female",
          age: 27,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الخليج العربي",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token10",
          circle_id: 1,
        },
        {
          N_Id: 1000000011,
          name: "عماد عبد الرحمن",
          email: "emad.abdelrahman@gmail.com",
          gender: "Male",
          age: 45,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الفاتح",
          isOrganizer: false,
          password: "password123",
          otp: "123456",
          token: "token11",
          circle_id: 2,
        },
        {
          N_Id: 1000000012,
          name: "هالة سامي",
          email: "hala.sami@gmail.com",
          gender: "Female",
          age: 30,
          city: "الزرقاء",
          religion: "الإسلام",
          polling_address: "شارع فلسطين",
          isOrganizer: true,
          password: "password123",
          otp: "234567",
          token: "token12",
          circle_id: 3,
        },
        {
          N_Id: 1000000013,
          name: "خالد عيسى",
          email: "khaled.issa@gmail.com",
          gender: "Male",
          age: 34,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الشهداء",
          isOrganizer: false,
          password: "password123",
          otp: "345678",
          token: "token13",
          circle_id: 1,
        },
        {
          N_Id: 1000000014,
          name: "سلمي رامي",
          email: "salma.rami@gmail.com",
          gender: "Female",
          age: 26,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الستين",
          isOrganizer: true,
          password: "password123",
          otp: "456789",
          token: "token14",
          circle_id: 2,
        },
        {
          N_Id: 1000000015,
          name: "عدنان زكريا",
          email: "adnan.zakaria@gmail.com",
          gender: "Male",
          age: 37,
          city: "الزرقاء",
          religion: "الإسلام",
          polling_address: "شارع المطار",
          isOrganizer: false,
          password: "password123",
          otp: "567890",
          token: "token15",
          circle_id: 3,
        },
        {
          N_Id: 1000000016,
          name: "ياسمين حسني",
          email: "yasmin.hossny@gmail.com",
          gender: "Female",
          age: 33,
          city: "عمان ",
          religion: "الإسلام",
          polling_address: "شارع القبلتين",
          isOrganizer: true,
          password: "password123",
          otp: "678901",
          token: "token16",
          circle_id: 1,
        },
        {
          N_Id: 1000000017,
          name: "جمال زين",
          email: "jamal.zein@gmail.com",
          gender: "Male",
          age: 42,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الجلاء",
          isOrganizer: false,
          password: "password123",
          otp: "789012",
          token: "token17",
          circle_id: 2,
        },
        {
          N_Id: 1000000018,
          name: "إيمان مصطفى",
          email: "eman.mustafa@gmail.com",
          gender: "Female",
          age: 29,
          city: "الزرقاء",
          religion: "الإسلام",
          polling_address: "شارع ابن تيمية",
          isOrganizer: true,
          password: "password123",
          otp: "890123",
          token: "token18",
          circle_id: 3,
        },
        {
          N_Id: 1000000019,
          name: "حسام سامي",
          email: "hossam.sami@gmail.com",
          gender: "Male",
          age: 31,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع المدارس",
          isOrganizer: false,
          password: "password123",
          otp: "901234",
          token: "token19",
          circle_id: 1,
        },
        {
          N_Id: 1000000020,
          name: "رغدة يوسف",
          email: "raghada.youssef@gmail.com",
          gender: "Female",
          age: 24,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع التلال",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token20",
          circle_id: 1,
        },
        {
          N_Id: 1000000021,
          name: "سعيد عبيد",
          email: "said.obeid@gmail.com",
          gender: "Male",
          age: 39,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع محمد الخامس",
          isOrganizer: false,
          password: "password123",
          otp: "123456",
          token: "token21",
          circle_id: 2,
        },
        {
          N_Id: 1000000022,
          name: "شيماء عبد الله",
          email: "shaimaa.abdullah@gmail.com",
          gender: "Female",
          age: 32,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الزيتون",
          isOrganizer: true,
          password: "password123",
          otp: "234567",
          token: "token22",
          circle_id: 2,
        },
        {
          N_Id: 1000000023,
          name: "توفيق بدر",
          email: "tawfiq.badr@gmail.com",
          gender: "Male",
          age: 41,
          city: "الزرقاء",
          religion: "الإسلام",
          polling_address: "شارع العودة",
          isOrganizer: false,
          password: "password123",
          otp: "345678",
          token: "token23",
          circle_id: 3,
        },
        {
          N_Id: 1000000024,
          name: "سندس طارق",
          email: "sundus.tariq@gmail.com",
          gender: "Female",
          age: 28,
          city: "الزرقاء",
          religion: "الإسلام",
          polling_address: "شارع القدس",
          isOrganizer: true,
          password: "password123",
          otp: "456789",
          token: "token24",
          circle_id: 3,
        },
        {
          N_Id: 1000000025,
          name: "سمير ناصر",
          email: "sameer.nasser@gmail.com",
          gender: "Male",
          age: 36,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الملكة رانيا",
          isOrganizer: false,
          password: "password123",
          otp: "567890",
          token: "token25",
          circle_id: 1,
        },
        {
          N_Id: 1000000026,
          name: "غادة زهران",
          email: "ghada.zahran@gmail.com",
          gender: "Female",
          age: 25,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الحبيب بورقيبة",
          isOrganizer: true,
          password: "password123",
          otp: "678901",
          token: "token26",
          circle_id: 1,
        },
        {
          N_Id: 1000000027,
          name: "بدر الدين عبد اللطيف",
          email: "badr.aldin.abdellatif@gmail.com",
          gender: "Male",
          age: 43,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الملك عبد العزيز",
          isOrganizer: false,
          password: "password123",
          otp: "789012",
          token: "token27",
          circle_id: 1,
        },
        {
          N_Id: 1000000028,
          name: "عائشة حسين",
          email: "aisha.hussein@gmail.com",
          gender: "Female",
          age: 34,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع القصر",
          isOrganizer: true,
          password: "password123",
          otp: "890123",
          token: "token28",
          circle_id: 2,
        },
        {
          N_Id: 1000000029,
          name: "عبد الرحمن الصادق",
          email: "abdulrahman.sadiq@gmail.com",
          gender: "Male",
          age: 50,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع عبد الحميد",
          isOrganizer: false,
          password: "password123",
          otp: "901234",
          token: "token29",
          circle_id: 2,
        },
        {
          N_Id: 1000000030,
          name: "جميلة حسن",
          email: "jamila.hassan@gmail.com",
          gender: "Female",
          age: 27,
          city: "الزرقاء",
          religion: "الإسلام",
          polling_address: "شارع الحرية",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token30",
          circle_id: 3,
        },
        {
          N_Id: 1000000031,
          name: "مازن فهد",
          email: "mazen.fahd@gmail.com",
          gender: "Male",
          age: 31,
          city: "الزرقاء",
          religion: "الإسلام",
          polling_address: "شارع الأمير سلطان",
          isOrganizer: false,
          password: "password123",
          otp: "123456",
          token: "token31",
          circle_id: 3,
        },
        {
          N_Id: 1000000032,
          name: "نادية عبد الرحمن",
          email: "nadia.abdelrahman@gmail.com",
          gender: "Female",
          age: 29,
          city: "الزرقاء",
          religion: "الإسلام",
          polling_address: "شارع السيب",
          isOrganizer: true,
          password: "password123",
          otp: "234567",
          token: "token32",
          circle_id: 3,
        },
        {
          N_Id: 1000000033,
          name: "سليمان خليل",
          email: "sulaiman.khalil@gmail.com",
          gender: "Male",
          age: 46,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع المدينة",
          isOrganizer: false,
          password: "password123",
          otp: "345678",
          token: "token33",
          circle_id: 1,
        },
        {
          N_Id: 1000000034,
          name: "جميلة سعيد",
          email: "jamila.saeed@gmail.com",
          gender: "Female",
          age: 37,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الجمهورية",
          isOrganizer: true,
          password: "password123",
          otp: "456789",
          token: "token34",
          circle_id: 1,
        },
        {
          N_Id: 1000000035,
          name: "رائد علي",
          email: "raed.ali@gmail.com",
          gender: "Male",
          age: 30,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الشيخ زايد",
          isOrganizer: false,
          password: "password123",
          otp: "567890",
          token: "token35",
          circle_id: 2,
        },
        {
          N_Id: 1000000036,
          name: "منال جابر",
          email: "manal.jaber@gmail.com",
          gender: "Female",
          age: 33,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الجامعة",
          isOrganizer: true,
          password: "password123",
          otp: "678901",
          token: "token36",
          circle_id: 2,
        },
        {
          N_Id: 1000000037,
          name: "رغد سامي",
          email: "raghad.sami@gmail.com",
          gender: "Female",
          age: 25,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الجهراء",
          isOrganizer: false,
          password: "password123",
          otp: "789012",
          token: "token37",
          circle_id: 2,
        },
        {
          N_Id: 1000000038,
          name: "سعيد زكي",
          email: "saeed.zaki@gmail.com",
          gender: "Male",
          age: 40,
          city: "الزرقاء",
          religion: "الإسلام",
          polling_address: "شارع البحر",
          isOrganizer: true,
          password: "password123",
          otp: "890123",
          token: "token38",
          circle_id: 3,
        },
        {
          N_Id: 1000000039,
          name: "عمر خالد",
          email: "omar.khalid@gmail.com",
          gender: "Male",
          age: 42,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الاستقلال",
          isOrganizer: false,
          password: "password123",
          otp: "901234",
          token: "token39",
          circle_id: 1,
        },
        {
          N_Id: 1000000040,
          name: "عبير رامي",
          email: "abeer.rami@gmail.com",
          gender: "Female",
          age: 26,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الجميزة",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token40",
          circle_id: 1,
        },
        {
          N_Id: 1000000041,
          name: "خالد محمود",
          email: "khaled.mahmoud@gmail.com",
          gender: "Male",
          age: 35,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع السلام",
          isOrganizer: false,
          password: "password123",
          otp: "123456",
          token: "token41",
          circle_id: 2,
        },
        {
          N_Id: 1000000042,
          name: "نور الهدى",
          email: "noor.aldha@gmail.com",
          gender: "Female",
          age: 30,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع التعاون",
          isOrganizer: true,
          password: "password123",
          otp: "234567",
          token: "token42",
          circle_id: 2,
        },
        {
          N_Id: 1000000043,
          name: "سمية عادل",
          email: "somiya.adel@gmail.com",
          gender: "Female",
          age: 29,
          city: "الزرقاء",
          religion: "الإسلام",
          polling_address: "شارع الأمير عبد الله",
          isOrganizer: false,
          password: "password123",
          otp: "345678",
          token: "token43",
          circle_id: 3,
        },
        {
          N_Id: 1000000044,
          name: "سعيد فهمي",
          email: "saeed.fahmy@gmail.com",
          gender: "Male",
          age: 41,
          city: "الزرقاء",
          religion: "الإسلام",
          polling_address: "شارع المعرض",
          isOrganizer: true,
          password: "password123",
          otp: "456789",
          token: "token44",
          circle_id: 3,
        },
        {
          N_Id: 1000000045,
          name: "جميل زكريا",
          email: "jameel.zakaria@gmail.com",
          gender: "Male",
          age: 33,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الرينبو",
          isOrganizer: false,
          password: "password123",
          otp: "567890",
          token: "token45",
          circle_id: 1,
        },
        {
          N_Id: 1000000046,
          name: "ميساء عزيز",
          email: "mayasa.aziz@gmail.com",
          gender: "Female",
          age: 27,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الجمال",
          isOrganizer: true,
          password: "password123",
          otp: "678901",
          token: "token46",
          circle_id: 1,
        },
        {
          N_Id: 1000000047,
          name: "خالد عبد الله",
          email: "khaled.abdallah@gmail.com",
          gender: "Male",
          age: 37,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الحسن",
          isOrganizer: false,
          password: "password123",
          otp: "789012",
          token: "token47",
          circle_id: 1,
        },
        {
          N_Id: 1000000048,
          name: "بثينة عيسى",
          email: "buthaina.issa@gmail.com",
          gender: "Female",
          age: 26,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع السعدون",
          isOrganizer: true,
          password: "password123",
          otp: "890123",
          token: "token48",
          circle_id: 1,
        },
        {
          N_Id: 1000000049,
          name: "رامي عبد الرحمن",
          email: "rami.abdulrahman@gmail.com",
          gender: "Male",
          age: 32,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "شارع الخليل",
          isOrganizer: false,
          password: "password123",
          otp: "901234",
          token: "token49",
          circle_id: 2,
        },
        {
          N_Id: 1000000050,
          name: "فاطمة حسن",
          email: "fatima.hassan@gmail.com",
          gender: "Female",
          age: 28,
          city: "الخرطوم",
          religion: "الإسلام",
          polling_address: "شارع الثورة",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        // // دائرة عمان الاولى/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        // // قائمة 1 العزم
        {
          N_Id: 1000000100,
          name: "احمد حمد أبو زيد",
          email: "Ahmad.Hamad@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        {
          N_Id: 1000000101,
          name: "مجدي عبد المعطي الشويكي",
          email: "majdi@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        {
          N_Id: 1000000102,
          name: "محمد أحمد المحارمة",
          email: "mohammad@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        {
          N_Id: 1000000103,
          name: "مثقال عويمر المشارقة",
          email: "mithqal@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        {
          N_Id: 1000000104,
          name: "ضحى ابو حماد",
          email: "Doha@gmail.com",
          gender: "Female",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        {
          N_Id: 1000000105,
          name: "محمد حمدان ابو سرحان",
          email: "mohamadd2@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        // قائمة2  الاتحاد
        {
          N_Id: 1000000106,
          name: "مرزوق الهبارنة",
          email: "marzooq@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        {
          N_Id: 1000000107,
          name: "فائق البستنجي ",
          email: "faiq@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        {
          N_Id: 1000000108,
          name: "سهام الشديفات",
          email: "Seham@gmail.com",
          gender: "Female",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        {
          N_Id: 1000000109,
          name: "علي فهد الزيود",
          email: "ali@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        {
          N_Id: 1000000110,
          name: "اياد القزعة",
          email: "eyad@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        {
          N_Id: 1000000111,
          name: "عساف الشوابكة ",
          email: "asaf@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        //قائمة  3"العهد"
        {
          N_Id: 1000000112,
          name: "أحمد الهميسات",
          email: "ahmad@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        {
          N_Id: 1000000113,
          name: "صايل الزعبي",
          email: "sail@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        {
          N_Id: 1000000114,
          name: "عبدالله الخصيلات ",
          email: "abd-khsilat@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        {
          N_Id: 1000000115,
          name: "غالب الشلالفة ",
          email: "galeb@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        {
          N_Id: 1000000116,
          name: " محمد محمود الزيود",
          email: "mhamad.zyod@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        {
          N_Id: 1000000117,
          name: " ابتسام عثمان صالح",
          email: "ibtesam@gmail.com",
          gender: "Female",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 1,
        },
        // // دائرة عمان الثانية/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        // نماء والعمل
        //
        {
          N_Id: 1000000200,
          name: " بسام عبدالله القطامي",
          email: "bassammm@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 2,
        },
        {
          N_Id: 1000000201,
          name: " حاتم عبدالله الرمحي",
          email: "hatem-abdalla@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 2,
        },
        {
          N_Id: 1000000202,
          name: "معتصم حسن الرمحي",
          email: "mutaseemmm@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 2,
        },
        {
          N_Id: 1000000203,
          name: " حمزة الشوابكة",
          email: "hamzaaaa-sh@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 2,
        },
        {
          N_Id: 1000000204,
          name: " مي السعود",
          email: "maii-suaad@gmail.com",
          gender: "Female",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 2,
        },
        {
          N_Id: 1000000205,
          name: "مهند الدبابنة ",
          email: "muhannad-dababnah@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 2,
        },
        {
          N_Id: 1000000206,
          name: " جواد الدباس",
          email: "jawaad@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 2,
        },
        {
          N_Id: 1000000207,
          name: "  مجدي ابو عدية",
          email: "majdiiii@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 2,
        },
        // /////////////////////////////////////////////
        // الوحدة
        {
          N_Id: 1000000208,
          name: "عدي عبد الرزاق",
          email: "oadaii@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 2,
        },
        {
          N_Id: 1000000209,
          name: " زهير حبش",
          email: "zohair@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 2,
        },
        {
          N_Id: 1000000210,
          name: "  لؤي الرمحي",
          email: "loaai-romhi@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 2,
        },
        {
          N_Id: 1000000211,
          name: "  نيفين سمير الشيخ",
          email: "nivien-sameer@gmail.com",
          gender: "Female",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 2,
        },
        {
          N_Id: 1000000212,
          name: "  خليل عليان",
          email: "khaleel-elian@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 2,
        },
        {
          N_Id: 1000000213,
          name: "امين عرار",
          email: "ameen-jaraar@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 2,
        },
        {
          N_Id: 1000000214,
          name: "محمد الفرارجة",
          email: "mo-fararja@gmail.com",
          gender: "Male",
          age: 28,
          city: "عمان",
          religion: "الإسلام",
          polling_address: "",
          isOrganizer: true,
          password: "password123",
          otp: "012345",
          token: "token50",
          circle_id: 2,
        },
      ]);
    });
};
