exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("Lists")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("Lists").insert([
        {
          list_name: "قائمة الأمل",
          list_type: "local",
          logo: "logo1.png",
          candidate_id: 1000000048,
          file_path: "path/to/file1.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة المستقبل",
          list_type: "party",
          logo: "logo2.png",
          candidate_id: 1000000043,
          file_path: "path/to/file2.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة الوحدة",
          list_type: "local",
          logo: "logo3.png",
          candidate_id: 1000000042,
          file_path: "path/to/file3.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة الإنجاز",
          list_type: "party",
          logo: "logo4.png",
          candidate_id: 1000000036,
          file_path: "path/to/file4.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة التنمية",
          list_type: "local",
          logo: "logo5.png",
          candidate_id: 1000000029,
          file_path: "path/to/file5.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة التغيير",
          list_type: "party",
          logo: "logo6.png",
          candidate_id: 1000000028,
          file_path: "path/to/file6.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة الأمل الجديد",
          list_type: "local",
          logo: "logo7.png",
          candidate_id: 1000000025,
          file_path: "path/to/file7.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة القيادة",
          list_type: "party",
          logo: "logo8.png",
          candidate_id: 1000000021,
          file_path: "path/to/file8.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة الريادة",
          list_type: "local",
          logo: "logo9.png",
          candidate_id: 1000000020,
          file_path: "path/to/file9.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة النهوض",
          list_type: "party",
          logo: "logo10.png",
          candidate_id: 1000000019,
          file_path: "path/to/file10.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة الطموح",
          list_type: "local",
          logo: "logo11.png",
          candidate_id: 1000000018,
          file_path: "path/to/file11.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة الإصلاح",
          list_type: "party",
          logo: "logo12.png",
          candidate_id: 1000000017,
          file_path: "path/to/file12.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة التعاون",
          list_type: "local",
          logo: "logo13.png",
          candidate_id: 1000000016,
          file_path: "path/to/file13.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة الاستقلال",
          list_type: "party",
          logo: "logo14.png",
          candidate_id: 1000000015,
          file_path: "path/to/file14.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة الازدهار",
          list_type: "local",
          logo: "logo15.png",
          candidate_id: 1000000014,
          file_path: "path/to/file15.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة النهضة",
          list_type: "party",
          logo: "logo16.png",
          candidate_id: 1000000011,
          file_path: "path/to/file16.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة التقدم",
          list_type: "local",
          logo: "logo17.png",
          candidate_id: 1000000010,
          file_path: "path/to/file17.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة الأمان",
          list_type: "party",
          logo: "logo18.png",
          candidate_id: 1000000009,
          file_path: "path/to/file18.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة الأفق",
          list_type: "local",
          logo: "logo19.png",
          candidate_id: 1000000001,
          file_path: "path/to/file19.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة الرفاه",
          list_type: "party",
          logo: "logo20.png",
          candidate_id: 1000000002,
          file_path: "path/to/file20.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة الرؤية",
          list_type: "local",
          logo: "logo21.png",
          candidate_id: 1000000003,
          file_path: "path/to/file21.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة النمو",
          list_type: "party",
          logo: "logo22.png",
          candidate_id: 1000000004,
          file_path: "path/to/file22.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة الشراكة",
          list_type: "local",
          logo: "logo23.png",
          candidate_id: 1000000005,
          file_path: "path/to/file23.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة الأجيال",
          list_type: "party",
          logo: "logo24.png",
          candidate_id: 1000000005,
          file_path: "path/to/file24.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة التماسك",
          list_type: "local",
          logo: "logo25.png",
          candidate_id: 1000000006,
          file_path: "path/to/file25.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة الانسجام",
          list_type: "party",
          logo: "logo26.png",
          candidate_id: 1000000007,
          file_path: "path/to/file26.pdf",
          status: "pending",
        },
        {
          list_name: "قائمة القيادة الحكيمة",
          list_type: "local",
          logo: "logo27.png",
          candidate_id: 1000000008,
          file_path: "path/to/file27.pdf",
          status: "pending",
        },
      ]);
    });
};
